# Generated by Django 5.2.6 on 2026-01-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carinventury'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInventury',
            new_name='CarInventory',
        ),
    ]
